server:
  port: 10010
spring:
  application:
    name: gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  retryable: true # 开启ribbon负载均衡和熔断
  prefix: /api # 全局路径匹配前缀
  routes:
    user-service:
      path: /user/**
      service-id: user-service
      strip-prefix: false
ribbon:
  #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  ConnectTimeout: 500 # Ribbon的连接超时时间
  ReadTimeout: 2000 # Ribbon的数据读取超时时间
  OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
  MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
  MaxAutoRetries: 0 # 对当前实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000 # 设置hystrix的超时时间为6000ms