server:
  port: 8080
spring:
  application:
    name: consumer-demo
  cloud:
    loadbalancer:
      retry:
        enabled: true # 开启重试机制 默认开启
eureka:
  client:
    registry-fetch-interval-seconds: 5  # 每隔5秒重新获取并更新数据
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 4 # 10秒即过期
    lease-renewal-interval-in-seconds: 2 # 5秒一次心跳
feign:
  hystrix:
    enabled: true
user-service: # 使用ribbon负载均衡规则，默认轮询
  ribbon:
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    ConnectTimeout: 500 # Ribbon的连接超时时间
    ReadTimeout: 2000 # Ribbon的数据读取超时时间
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
    MaxAutoRetries: 0 # 对当前实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000 # 设置hystrix的超时时间为6000ms
