server:
  port: 10086
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:${server.port}/eureka
  server:
    enable-self-preservation: false # 关闭自我保护机制, 没有down状态
    eviction-interval-timer-in-ms: 5000 # 扫描失效服务的间隔时间（缺省为60*1000ms）